#!/usr/bin/env python3
"""
Retrieve the list of FITS image filenames generated by the last multrun created by MookodiCameraServer, and display
the filenames.
"""
from mookodi.camera.client.client import Client

# Create client
c= Client()
l = c.get_image_filenames()
filename_count = len(l)
print ("There are " + repr(filename_count) + " Image Filenames:")
for s in l:
    print ("Image Filename:" + s)
