#!/usr/bin/env python3
"""
Command line tool to get the last FITS image filename generated by the MookodiCameraServer.
"""
from mookodi.camera.client.client import Client

# Create client
c= Client()
s = c.get_last_image_filename()
print ("Last Image Filename:" + s)
