#!/bin/csh
if ( ! $?SRC_HOME ) then
   echo "Define SRC_HOME to be the parent of your Mookodi checkout before running this script."
   exit 1
endif
setenv MOOKODI_SRC_HOME	${SRC_HOME}/Mookodi
mkdir ${MOOKODI_SRC_HOME}/bin
mkdir ${MOOKODI_SRC_HOME}/bin/lib
mkdir ${MOOKODI_SRC_HOME}/bin/lib/x86_64-linux
mkdir ${MOOKODI_SRC_HOME}/bin/mookodi/
mkdir ${MOOKODI_SRC_HOME}/bin/mookodi/camera/
mkdir ${MOOKODI_SRC_HOME}/bin/mookodi/camera/server
mkdir ${MOOKODI_SRC_HOME}/bin/mookodi/camera/server/interface/
mkdir ${MOOKODI_SRC_HOME}/bin/mookodi/camera/server/x86_64-linux
mkdir ${MOOKODI_SRC_HOME}/bin/mookodi/camera/server/interface/x86_64-linux
mkdir ${MOOKODI_SRC_HOME}/bin/mookodi/ccd
mkdir ${MOOKODI_SRC_HOME}/bin/mookodi/ccd/c
mkdir ${MOOKODI_SRC_HOME}/bin/mookodi/ccd/test
mkdir ${MOOKODI_SRC_HOME}/bin/mookodi/ccd/c/x86_64-linux
mkdir ${MOOKODI_SRC_HOME}/bin/mookodi/ccd/test/x86_64-linux
